<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PendudukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('penduduk')->insert([
            [
                'id' => 1,
                'uuid' => Str::uuid(),
                'nik' => '160653291086170',
                'nama_lengkap' => 'Tirtayasa Samosir',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1959-05-26',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'A',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 8,
                'pendidikan_id' => 4,
                'foto' => 'default.jpg',
                'tinggi_badan' => 183,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'uuid' => Str::uuid(),
                'nik' => '558888052165151',
                'nama_lengkap' => 'Abyasa Prayoga',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1999-06-16',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 183,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'uuid' => Str::uuid(),
                'nik' => '368713764996523',
                'nama_lengkap' => 'Paris Permadi, S.T.',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1992-10-24',
                'tempat_lahir' => 'Madiun',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 5,
                'pendidikan_id' => 9,
                'foto' => 'default.jpg',
                'tinggi_badan' => 183,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'uuid' => Str::uuid(),
                'nik' => '421824110907287',
                'nama_lengkap' => 'Agnes Mansur',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2016-02-17',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 8,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 152,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'uuid' => Str::uuid(),
                'nik' => '485816103865677',
                'nama_lengkap' => 'Najwa Salahudin',
                'agama' => 'Budha',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1977-11-10',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 140,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'uuid' => Str::uuid(),
                'nik' => '385096283163383',
                'nama_lengkap' => 'R. Uda Marpaung, S.H.',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1946-05-09',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 185,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'uuid' => Str::uuid(),
                'nik' => '581837187661212',
                'nama_lengkap' => 'Gawati Putra, S.T.',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1952-05-10',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'A',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 8,
                'foto' => 'default.jpg',
                'tinggi_badan' => 152,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'uuid' => Str::uuid(),
                'nik' => '039960888695375',
                'nama_lengkap' => 'Ir. Jarwi Agustina',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1963-04-13',
                'tempat_lahir' => 'Lumajang',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 182,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'uuid' => Str::uuid(),
                'nik' => '131510626639659',
                'nama_lengkap' => 'Dt. Lamar Oktaviani',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1954-07-22',
                'tempat_lahir' => 'Lumajang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 9,
                'foto' => 'default.jpg',
                'tinggi_badan' => 153,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'uuid' => Str::uuid(),
                'nik' => '672684837317709',
                'nama_lengkap' => 'R. Kusuma Nainggolan',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1967-11-07',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 1,
                'foto' => 'default.jpg',
                'tinggi_badan' => 185,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'uuid' => Str::uuid(),
                'nik' => '990066860440877',
                'nama_lengkap' => 'Oliva Nashiruddin',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1950-06-29',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 1,
                'pendidikan_id' => 10,
                'foto' => 'default.jpg',
                'tinggi_badan' => 150,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'uuid' => Str::uuid(),
                'nik' => '576537626589935',
                'nama_lengkap' => 'Restu Suryatmi',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2016-10-26',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'B',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 156,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'uuid' => Str::uuid(),
                'nik' => '386586470680647',
                'nama_lengkap' => 'Ir. Zizi Wacana',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1962-06-18',
                'tempat_lahir' => 'Madiun',
                'gol_darah' => 'B',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 179,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'uuid' => Str::uuid(),
                'nik' => '535382812835356',
                'nama_lengkap' => 'Indah Firgantoro',
                'agama' => 'Budha',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2024-06-28',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 10,
                'foto' => 'default.jpg',
                'tinggi_badan' => 148,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'uuid' => Str::uuid(),
                'nik' => '889828493755358',
                'nama_lengkap' => 'Maryadi Mustofa',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1970-08-24',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'O',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 140,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'uuid' => Str::uuid(),
                'nik' => '526574731912611',
                'nama_lengkap' => 'Ratna Palastri',
                'agama' => 'Budha',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1953-08-21',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 5,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 143,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'uuid' => Str::uuid(),
                'nik' => '383924520138449',
                'nama_lengkap' => 'Silvia Yulianti',
                'agama' => 'Islam',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2008-02-26',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 2,
                'foto' => 'default.jpg',
                'tinggi_badan' => 178,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'uuid' => Str::uuid(),
                'nik' => '098247977779275',
                'nama_lengkap' => 'Darmanto Wijaya',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1979-01-15',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 1,
                'foto' => 'default.jpg',
                'tinggi_badan' => 174,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'uuid' => Str::uuid(),
                'nik' => '010114064916318',
                'nama_lengkap' => 'Zalindra Yuliarti',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1996-05-03',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 1,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 175,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'uuid' => Str::uuid(),
                'nik' => '046742671251666',
                'nama_lengkap' => 'Purwanto Palastri, S.T.',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2021-01-16',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 8,
                'foto' => 'default.jpg',
                'tinggi_badan' => 170,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'uuid' => Str::uuid(),
                'nik' => '554374856644457',
                'nama_lengkap' => 'Purwanto Saefullah',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1979-06-01',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 5,
                'pendidikan_id' => 10,
                'foto' => 'default.jpg',
                'tinggi_badan' => 180,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'uuid' => Str::uuid(),
                'nik' => '280624353580768',
                'nama_lengkap' => 'Hj. Halima Zulaika',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2010-06-22',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 5,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 153,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'uuid' => Str::uuid(),
                'nik' => '281735553879093',
                'nama_lengkap' => 'Gilda Suartini',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1961-08-20',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 8,
                'pendidikan_id' => 7,
                'foto' => 'default.jpg',
                'tinggi_badan' => 158,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'uuid' => Str::uuid(),
                'nik' => '115800494765714',
                'nama_lengkap' => 'Soleh Farida, S.Sos',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2000-03-21',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 8,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 161,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'uuid' => Str::uuid(),
                'nik' => '740614236364395',
                'nama_lengkap' => 'Raisa Pangestu',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1969-03-30',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 4,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 165,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'uuid' => Str::uuid(),
                'nik' => '407170001508497',
                'nama_lengkap' => 'Balamantri Pangestu',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2004-03-18',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 184,
                'status' => 'mati',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'uuid' => Str::uuid(),
                'nik' => '749781399930336',
                'nama_lengkap' => 'Embuh Hassanah',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1942-04-08',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 10,
                'foto' => 'default.jpg',
                'tinggi_badan' => 157,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'uuid' => Str::uuid(),
                'nik' => '274088937508457',
                'nama_lengkap' => 'Candrakanta Suryono, S.IP',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1971-11-15',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 10,
                'foto' => 'default.jpg',
                'tinggi_badan' => 170,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'uuid' => Str::uuid(),
                'nik' => '233941159861004',
                'nama_lengkap' => 'Karen Aryani',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2011-05-06',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 9,
                'pendidikan_id' => 4,
                'foto' => 'default.jpg',
                'tinggi_badan' => 181,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'uuid' => Str::uuid(),
                'nik' => '249964301952867',
                'nama_lengkap' => 'R. Rachel Nasyidah, S.Gz',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1954-03-07',
                'tempat_lahir' => 'Lumajang',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 7,
                'pendidikan_id' => 4,
                'foto' => 'default.jpg',
                'tinggi_badan' => 147,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'uuid' => Str::uuid(),
                'nik' => '114443393956634',
                'nama_lengkap' => 'Adhiarja Wahyuni',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2000-10-06',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 1,
                'foto' => 'default.jpg',
                'tinggi_badan' => 183,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'uuid' => Str::uuid(),
                'nik' => '769591916091907',
                'nama_lengkap' => 'Dr. Mumpuni Budiyanto',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2020-10-29',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'B',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 9,
                'foto' => 'default.jpg',
                'tinggi_badan' => 154,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'uuid' => Str::uuid(),
                'nik' => '116771779380734',
                'nama_lengkap' => 'Purwa Hariyah',
                'agama' => 'Budha',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1939-10-31',
                'tempat_lahir' => 'Madiun',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 9,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 152,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'uuid' => Str::uuid(),
                'nik' => '130394508688173',
                'nama_lengkap' => 'Drs. Ratna Pradipta, S.Pd',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2018-02-17',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 157,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'uuid' => Str::uuid(),
                'nik' => '661519579870303',
                'nama_lengkap' => 'Vera Farida',
                'agama' => 'Budha',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2018-12-14',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 5,
                'pendidikan_id' => 8,
                'foto' => 'default.jpg',
                'tinggi_badan' => 169,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'uuid' => Str::uuid(),
                'nik' => '202583978807012',
                'nama_lengkap' => 'Samsul Adriansyah',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1962-05-21',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 4,
                'foto' => 'default.jpg',
                'tinggi_badan' => 157,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'uuid' => Str::uuid(),
                'nik' => '731254722130994',
                'nama_lengkap' => 'Puti Silvia Megantara, S.Kom',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1986-07-05',
                'tempat_lahir' => 'Lumajang',
                'gol_darah' => 'B',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 7,
                'foto' => 'default.jpg',
                'tinggi_badan' => 181,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'uuid' => Str::uuid(),
                'nik' => '616576961102179',
                'nama_lengkap' => 'Ellis Setiawan',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1996-02-07',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 9,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 150,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'uuid' => Str::uuid(),
                'nik' => '807738376104846',
                'nama_lengkap' => 'Syahrini Pudjiastuti, S.E.I',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1956-07-31',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 157,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 40,
                'uuid' => Str::uuid(),
                'nik' => '947722934096534',
                'nama_lengkap' => 'Cut Dian Wahyuni, S.E.I',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2000-10-07',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'O',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 182,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'uuid' => Str::uuid(),
                'nik' => '417144636994379',
                'nama_lengkap' => 'Zaenab Padmasari',
                'agama' => 'Islam',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1944-12-21',
                'tempat_lahir' => 'Madiun',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 7,
                'pendidikan_id' => 2,
                'foto' => 'default.jpg',
                'tinggi_badan' => 162,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 42,
                'uuid' => Str::uuid(),
                'nik' => '881245211607731',
                'nama_lengkap' => 'Hana Sudiati, M.TI.',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2003-09-22',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 164,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 43,
                'uuid' => Str::uuid(),
                'nik' => '607742728827582',
                'nama_lengkap' => 'Hana Widodo',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1968-08-18',
                'tempat_lahir' => 'Blitar',
                'gol_darah' => 'B',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 10,
                'foto' => 'default.jpg',
                'tinggi_badan' => 159,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 44,
                'uuid' => Str::uuid(),
                'nik' => '396523253607938',
                'nama_lengkap' => 'Tgk. Jelita Kuswoyo',
                'agama' => 'Islam',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1959-05-04',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 4,
                'pendidikan_id' => 8,
                'foto' => 'default.jpg',
                'tinggi_badan' => 182,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 45,
                'uuid' => Str::uuid(),
                'nik' => '804767345795802',
                'nama_lengkap' => 'Shakila Hardiansyah',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1937-03-04',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'A',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 1,
                'foto' => 'default.jpg',
                'tinggi_badan' => 177,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 46,
                'uuid' => Str::uuid(),
                'nik' => '614029369124157',
                'nama_lengkap' => 'dr. Tira Salahudin, M.Kom.',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1976-02-25',
                'tempat_lahir' => 'Pasuruan',
                'gol_darah' => 'B',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 7,
                'pendidikan_id' => 7,
                'foto' => 'default.jpg',
                'tinggi_badan' => 157,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 47,
                'uuid' => Str::uuid(),
                'nik' => '972911127548178',
                'nama_lengkap' => 'Dr. Humaira Kuswandari',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2019-03-06',
                'tempat_lahir' => 'Madiun',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai hidup',
                'pekerjaan_id' => 7,
                'pendidikan_id' => 8,
                'foto' => 'default.jpg',
                'tinggi_badan' => 143,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 48,
                'uuid' => Str::uuid(),
                'nik' => '345730774724127',
                'nama_lengkap' => 'Drs. Kenzie Sinaga, S.Kom',
                'agama' => 'Khonghucu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2000-10-06',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 2,
                'foto' => 'default.jpg',
                'tinggi_badan' => 142,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 49,
                'uuid' => Str::uuid(),
                'nik' => '309786173467474',
                'nama_lengkap' => 'Luis Utami',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2009-06-27',
                'tempat_lahir' => 'Madiun',
                'gol_darah' => 'A',
                'status_perkawinan' => 'cerai mati',
                'pekerjaan_id' => 10,
                'pendidikan_id' => 2,
                'foto' => 'default.jpg',
                'tinggi_badan' => 146,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 50,
                'uuid' => Str::uuid(),
                'nik' => '741105186977634',
                'nama_lengkap' => 'Ellis Widiastuti',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1993-12-23',
                'tempat_lahir' => 'Jabung',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 8,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 174,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
