<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PendudukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('penduduk')->insert([
            [
                'id' => 1,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123456',
                'nama_lengkap' => 'John Doe',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1990-01-01',
                'tempat_lahir' => 'Jakarta',
                'gol_darah' => 'A',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 1,
                'foto' => 'default.jpg',
                'tinggi_badan' => 170,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123457',
                'nama_lengkap' => 'Jane Doe',
                'agama' => 'Islam',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1992-02-02',
                'tempat_lahir' => 'Bandung',
                'gol_darah' => 'B',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 2,
                'foto' => 'default.jpg',
                'tinggi_badan' => 160,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123458',
                'nama_lengkap' => 'Michael Smith',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1988-03-03',
                'tempat_lahir' => 'Surabaya',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 1,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 175,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123459',
                'nama_lengkap' => 'Sarah Connor',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1995-04-04',
                'tempat_lahir' => 'Yogyakarta',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 4,
                'pendidikan_id' => 4,
                'foto' => 'default.jpg',
                'tinggi_badan' => 165,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123460',
                'nama_lengkap' => 'David Brown',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1993-05-05',
                'tempat_lahir' => 'Denpasar',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 5,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 180,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123461',
                'nama_lengkap' => 'Emily White',
                'agama' => 'Buddha',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1991-06-06',
                'tempat_lahir' => 'Medan',
                'gol_darah' => 'B',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 158,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123462',
                'nama_lengkap' => 'Liam Anderson',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1994-07-07',
                'tempat_lahir' => 'Makassar',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 7,
                'pendidikan_id' => 7,
                'foto' => 'default.jpg',
                'tinggi_badan' => 172,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123463',
                'nama_lengkap' => 'Olivia Johnson',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1996-08-08',
                'tempat_lahir' => 'Palembang',
                'gol_darah' => 'A',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 8,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 162,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123464',
                'nama_lengkap' => 'Noah Wilson',
                'agama' => 'Katolik',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1990-09-09',
                'tempat_lahir' => 'Semarang',
                'gol_darah' => 'B',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 2,
                'pendidikan_id' => 4,
                'foto' => 'default.jpg',
                'tinggi_badan' => 176,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123465',
                'nama_lengkap' => 'Ava Martinez',
                'agama' => 'Islam',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1993-10-10',
                'tempat_lahir' => 'Padang',
                'gol_darah' => 'O',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 9,
                'pendidikan_id' => 5,
                'foto' => 'default.jpg',
                'tinggi_badan' => 168,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123466',
                'nama_lengkap' => 'James Lee',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1987-11-11',
                'tempat_lahir' => 'Balikpapan',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 4,
                'pendidikan_id' => 6,
                'foto' => 'default.jpg',
                'tinggi_badan' => 174,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123467',
                'nama_lengkap' => 'Sophia Kim',
                'agama' => 'Buddha',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1997-12-12',
                'tempat_lahir' => 'Pontianak',
                'gol_darah' => 'B',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 6,
                'pendidikan_id' => 2,
                'foto' => 'default.jpg',
                'tinggi_badan' => 163,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123468',
                'nama_lengkap' => 'William Chen',
                'agama' => 'Konghucu',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1989-01-13',
                'tempat_lahir' => 'Manado',
                'gol_darah' => 'A',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 7,
                'pendidikan_id' => 1,
                'foto' => 'default.jpg',
                'tinggi_badan' => 169,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123469',
                'nama_lengkap' => 'Isabella Tan',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '1998-03-14',
                'tempat_lahir' => 'Solo',
                'gol_darah' => 'O',
                'status_perkawinan' => 'belum kawin',
                'pekerjaan_id' => 1,
                'pendidikan_id' => 3,
                'foto' => 'default.jpg',
                'tinggi_badan' => 159,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'uuid' => Str::uuid(),
                'nik' => '1234567890123470',
                'nama_lengkap' => 'Benjamin Harris',
                'agama' => 'Islam',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '1992-05-15',
                'tempat_lahir' => 'Malang',
                'gol_darah' => 'AB',
                'status_perkawinan' => 'kawin',
                'pekerjaan_id' => 3,
                'pendidikan_id' => 7,
                'foto' => 'default.jpg',
                'tinggi_badan' => 178,
                'status' => 'hidup',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
        ]);
    }
}
